Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig = px.line(
    df,
    "employment_income",
    "ma_limited_income_tax_credit",
    color="children",
    animation_frame="adults",
    labels=LABELS,
    title="Massachusetts Limited Income Credit",
    color_discrete_map=COLOR_MAP,
)
fig.update_layout(
    xaxis_tickformat="$,",
    yaxis_tickformat="$,",
    yaxis_range=[0, df.ma_limited_income_tax_credit.max()],
    plot_bgcolor="white",
    xaxis_gridcolor=LIGHT_GRAY,
    yaxis_gridcolor=LIGHT_GRAY,
)
set_bounds(fig, df.employment_income, df.ma_limited_income_tax_credit)
fig.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_2983/1981194212.py[0m in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0;31m fig = px.line(
[0m[1;32m      2[0m     [0mdf[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0;34m"employment_income"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0;34m"ma_limited_income_tax_credit"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0mcolor[0m[0;34m=[0m[0;34m"children"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/plotly/express/_chart_types.py[0m in [0;36mline[0;34m(data_frame, x, y, line_group, color, line_dash, symbol, hover_name, hover_data, custom_data, text, facet_row, facet_col, facet_col_wrap, facet_row_spacing, facet_col_spacing, error_x, error_x_minus, error_y, error_y_minus, animation_frame, animation_group, category_orders, labels, orientation, color_discrete_sequence, color_discrete_map, line_dash_sequence, line_dash_map, symbol_sequence, symbol_map, markers, log_x, log_y, range_x, range_y, line_shape, render_mode, title, template, width, height)[0m
[1;32m    262[0m     [0ma[0m [0mpolyline[0m [0mmark[0m [0;32min[0m [0;36m2[0m[0mD[0m [0mspace[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m    263[0m     """
[0;32m--> 264[0;31m     [0;32mreturn[0m [0mmake_figure[0m[0;34m([0m[0margs[0m[0;34m=[0m[0mlocals[0m[0;34m([0m[0;34m)[0m[0;34m,[0m [0mconstructor[0m[0;34m=[0m[0mgo[0m[0;34m.[0m[0mScatter[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    265[0m [0;34m[0m[0m
[1;32m    266[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/plotly/express/_core.py[0m in [0;36mmake_figure[0;34m(args, constructor, trace_patch, layout_patch)[0m
[1;32m   2088[0m     [0mapply_default_cascade[0m[0;34m([0m[0margs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2089[0m [0;34m[0m[0m
[0;32m-> 2090[0;31m     [0margs[0m [0;34m=[0m [0mbuild_dataframe[0m[0;34m([0m[0margs[0m[0;34m,[0m [0mconstructor[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2091[0m     [0;32mif[0m [0mconstructor[0m [0;32min[0m [0;34m[[0m[0mgo[0m[0;34m.[0m[0mTreemap[0m[0;34m,[0m [0mgo[0m[0;34m.[0m[0mSunburst[0m[0;34m,[0m [0mgo[0m[0;34m.[0m[0mIcicle[0m[0;34m][0m [0;32mand[0m [0margs[0m[0;34m[[0m[0;34m"path"[0m[0;34m][0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2092[0m         [0margs[0m [0;34m=[0m [0mprocess_dataframe_hierarchy[0m[0;34m([0m[0margs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/plotly/express/_core.py[0m in [0;36mbuild_dataframe[0;34m(args, constructor)[0m
[1;32m   1490[0m     [0;31m# now that things have been prepped, we do the systematic rewriting of `args`[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1491[0m [0;34m[0m[0m
[0;32m-> 1492[0;31m     df_output, wide_id_vars = process_args_into_dataframe(
[0m[1;32m   1493[0m         [0margs[0m[0;34m,[0m [0mwide_mode[0m[0;34m,[0m [0mvar_name[0m[0;34m,[0m [0mvalue_name[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1494[0m     )

[0;32m/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/plotly/express/_core.py[0m in [0;36mprocess_args_into_dataframe[0;34m(args, wide_mode, var_name, value_name)[0m
[1;32m   1211[0m                         [0;32mif[0m [0margument[0m [0;34m==[0m [0;34m"index"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1212[0m                             [0merr_msg[0m [0;34m+=[0m [0;34m"\n To use the index, pass it in directly as `df.index`."[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1213[0;31m                         [0;32mraise[0m [0mValueError[0m[0;34m([0m[0merr_msg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1214[0m                 [0;32melif[0m [0mlength[0m [0;32mand[0m [0mlen[0m[0;34m([0m[0mdf_input[0m[0;34m[[0m[0margument[0m[0;34m][0m[0;34m)[0m [0;34m!=[0m [0mlength[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1215[0m                     raise ValueError(

[0;31mValueError[0m: Value of 'y' is not the name of a column in 'data_frame'. Expected one of ['employment_income', 'de_income_tax', 'de_eitc', 'de_refundable_eitc', 'de_non_refundable_eitc', 'mtr', 'adults', 'children'] but received: ma_limited_income_tax_credit

