Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from policyengine_us.tools.documentation import (
    variable_summary,
    variation_chart,
)

variable_summary("snap_standard_deduction")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m/tmp/ipykernel_2279/703537161.py[0m in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0;31m from policyengine_us.tools.documentation import (
[0m[1;32m      2[0m     [0mvariable_summary[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0mvariation_chart[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m )
[1;32m      5[0m [0;34m[0m[0m

[0;32m~/work/policyengine-us/policyengine-us/policyengine_us/tools/documentation.py[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0;34m[0m[0m
[1;32m      8[0m [0;32mfrom[0m [0mpolicyengine_core[0m[0;34m.[0m[0menums[0m [0;32mimport[0m [0mEnum[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 9[0;31m from policyengine_core.charts import (
[0m[1;32m     10[0m     [0mLIGHTER_BLUE[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     11[0m     [0mLIGHT_BLUE[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: cannot import name 'LIGHTER_BLUE' from 'policyengine_core.charts' (/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/policyengine_core/charts/__init__.py)

