Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from policyengine_us.tools.documentation import (
    variable_summary,
    variation_chart,
)

variable_summary("ctc")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpolicyengine_us[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtools[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdocumentation[39;00m [38;5;28;01mimport[39;00m (
[1;32m      2[0m     variable_summary,
[1;32m      3[0m     variation_chart,
[1;32m      4[0m )
[1;32m      6[0m variable_summary([38;5;124m"[39m[38;5;124mctc[39m[38;5;124m"[39m)

File [0;32m~/work/policyengine-us/policyengine-us/policyengine_us/tools/documentation.py:9[0m
[1;32m      6[0m warnings[38;5;241m.[39mfilterwarnings([38;5;124m"[39m[38;5;124mignore[39m[38;5;124m"[39m)
[1;32m      8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpolicyengine_core[39;00m[38;5;21;01m.[39;00m[38;5;21;01menums[39;00m [38;5;28;01mimport[39;00m Enum
[0;32m----> 9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpolicyengine_core[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcharts[39;00m [38;5;28;01mimport[39;00m (
[1;32m     10[0m     LIGHTER_BLUE,
[1;32m     11[0m     LIGHT_BLUE,
[1;32m     12[0m     BLUE,
[1;32m     13[0m     DARK_BLUE,
[1;32m     14[0m     format_fig,
[1;32m     15[0m     display_fig,
[1;32m     16[0m )
[1;32m     17[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpolicyengine_us[39;00m[38;5;21;01m.[39;00m[38;5;21;01msystem[39;00m [38;5;28;01mimport[39;00m system
[1;32m     18[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpolicyengine_us[39;00m [38;5;28;01mimport[39;00m Simulation

[0;31mImportError[0m: cannot import name 'LIGHTER_BLUE' from 'policyengine_core.charts' (/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/policyengine_core/charts/__init__.py)

